# Site Settings
title: Gasbebe dev
email: 
description: Some text about your blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-125418989-1"

# User Settings
username: Gasbebe
user_description:
disqus_username: 

# Social Media
# Remove the item if you don't need it
github_username: Gasbebe
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
medium_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/



# Plugins
plugins:
  - jemoji
  - mathjax

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title : Shader
    url : /tags/#shader
  - title: Math
    url : /tags/#math
  - title : ETC
    url : /tags/#ETC

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
